-- 4 PHONGBAN
CREATE TABLE PHONGBAN(
	PB_MA VARCHAR(5) PRIMARY KEY,
	PB_TEN VARCHAR(150),
	PB_GHICHU VARCHAR(150)
);

INSERT INTO PHONGBAN Values ('PB001',N'Phòng kế hoạch tài chính','');
INSERT INTO PHONGBAN Values ('PB002',N'Phòng kỹ thuật','');

